GET http://localhost:4000/users

###

GET http://localhost:4000/users/

###

POST http://localhost:4000/users/
Content-Type: application/json

{
    "fullname": "Darren Petersen",
    "email": "darrenpetersen007@gmail.com",
    "password": "Lifechoices1234",
    "phone_number": "0787521530"
}

###

PATCH http://localhost:4000/users/
Content-Type: application/json

{
    "fullname": "Darren Petersen",
    "email": "darrenpetersen007@gmail.com",
    "password": "Lifechoices1234",
    "phone_number": "0787521530"
}

###

PUT http://localhost:4000/users/


###

DELETE http://localhost:4000/users/

###

GET http://localhost:4000/posts
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJmdWxsbmFtZSI6IkRhcnJlbiBQZXRlcnNlbiIsImVtYWlsIjoiZGFycmVucGV0ZXJzZW4wMDdAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkd2M3dTJEZVlLSXVMV2VURWMubm0xT0JvMk90cVpqV0Fxb3o4U0lPWnkwVC9GVzlpV2cuUWkiLCJwaG9uZV9udW1iZXIiOiIwNzg3NTIxNTMwIiwiY2FydCI6W10sIl9pZCI6IjYyMTYyYWQ1YWRlZmE4MzdiMGE4MjE5MiIsImpvaW5fZGF0ZSI6IjIwMjItMDItMjNUMTI6Mzg6NDUuOTQ4WiIsIl9fdiI6MH0.b8UCiLa3LaI72-lyEbVLuR7r4qxiAbQcWTh-Idob1e4

###

GET http://localhost:4000/posts/
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJmdWxsbmFtZSI6IkRhcnJlbiBQZXRlcnNlbiIsImVtYWlsIjoiZGFycmVucGV0ZXJzZW4wMDdAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkd2M3dTJEZVlLSXVMV2VURWMubm0xT0JvMk90cVpqV0Fxb3o4U0lPWnkwVC9GVzlpV2cuUWkiLCJwaG9uZV9udW1iZXIiOiIwNzg3NTIxNTMwIiwiY2FydCI6W10sIl9pZCI6IjYyMTYyYWQ1YWRlZmE4MzdiMGE4MjE5MiIsImpvaW5fZGF0ZSI6IjIwMjItMDItMjNUMTI6Mzg6NDUuOTQ4WiIsIl9fdiI6MH0.b8UCiLa3LaI72-lyEbVLuR7r4qxiAbQcWTh-Idob1e4


###

POST http://localhost:4000/posts/
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJmdWxsbmFtZSI6IkRhcnJlbiBQZXRlcnNlbiIsImVtYWlsIjoiZGFycmVucGV0ZXJzZW4wMDdAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkd2M3dTJEZVlLSXVMV2VURWMubm0xT0JvMk90cVpqV0Fxb3o4U0lPWnkwVC9GVzlpV2cuUWkiLCJwaG9uZV9udW1iZXIiOiIwNzg3NTIxNTMwIiwiY2FydCI6W10sIl9pZCI6IjYyMTYyYWQ1YWRlZmE4MzdiMGE4MjE5MiIsImpvaW5fZGF0ZSI6IjIwMjItMDItMjNUMTI6Mzg6NDUuOTQ4WiIsIl9fdiI6MH0.b8UCiLa3LaI72-lyEbVLuR7r4qxiAbQcWTh-Idob1e4
Content-Type: application/json

{
    "title": "sdfghjkiuytrfdxcsd",
    "body": "aasofoefmsoefm",
    "date": "",
    "author": "ayoooo"
}

###

PUT http://localhost:4000/posts/
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJmdWxsbmFtZSI6IkRhcnJlbiBQZXRlcnNlbiIsImVtYWlsIjoiZGFycmVucGV0ZXJzZW4wMDdAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkd2M3dTJEZVlLSXVMV2VURWMubm0xT0JvMk90cVpqV0Fxb3o4U0lPWnkwVC9GVzlpV2cuUWkiLCJwaG9uZV9udW1iZXIiOiIwNzg3NTIxNTMwIiwiY2FydCI6W10sIl9pZCI6IjYyMTYyYWQ1YWRlZmE4MzdiMGE4MjE5MiIsImpvaW5fZGF0ZSI6IjIwMjItMDItMjNUMTI6Mzg6NDUuOTQ4WiIsIl9fdiI6MH0.b8UCiLa3LaI72-lyEbVLuR7r4qxiAbQcWTh-Idob1e4
Content-Type: application/json

{
    "title": "Sun",
    "body": "I am always shinning",
    "date": "",
    "author": "2"
}

###

DELETE http://localhost:4000/posts/
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJmdWxsbmFtZSI6IkRhcnJlbiBQZXRlcnNlbiIsImVtYWlsIjoiZGFycmVucGV0ZXJzZW4wMDdAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkd2M3dTJEZVlLSXVMV2VURWMubm0xT0JvMk90cVpqV0Fxb3o4U0lPWnkwVC9GVzlpV2cuUWkiLCJwaG9uZV9udW1iZXIiOiIwNzg3NTIxNTMwIiwiY2FydCI6W10sIl9pZCI6IjYyMTYyYWQ1YWRlZmE4MzdiMGE4MjE5MiIsImpvaW5fZGF0ZSI6IjIwMjItMDItMjNUMTI6Mzg6NDUuOTQ4WiIsIl9fdiI6MH0.b8UCiLa3LaI72-lyEbVLuR7r4qxiAbQcWTh-Idob1e4
Content-Type: application/json

###
